//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogEntities : DbContext
    {
        public BlogEntities()
            : base("name=BlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ABOUTUS> ABOUTUS { get; set; }
        public DbSet<ABOUTUSCOUNTER> ABOUTUSCOUNTER { get; set; }
        public DbSet<BLOG> BLOG { get; set; }
        public DbSet<CATEGORIES> CATEGORIES { get; set; }
        public DbSet<DISEASES> DISEASES { get; set; }
        public DbSet<MAIL> MAIL { get; set; }
        public DbSet<MAILPARAMETER> MAILPARAMETER { get; set; }
        public DbSet<MAILQUEUE> MAILQUEUE { get; set; }
        public DbSet<MAINPAGESLIDER> MAINPAGESLIDER { get; set; }
        public DbSet<MEMBER> MEMBER { get; set; }
        public DbSet<PARAMETER> PARAMETER { get; set; }
        public DbSet<QUESTION> QUESTION { get; set; }
    }
}
