//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOG
    {
        public int ID { get; set; }
        public string IMAGE { get; set; }
        public string TITLE { get; set; }
        public string ALT { get; set; }
        public bool ISACTIVE { get; set; }
        public string MAINTEXT { get; set; }
        public int SORT { get; set; }
        public System.DateTime DATE { get; set; }
        public bool ISVIDEO { get; set; }
        public string VIDEOCODE { get; set; }
        public string URLSEO { get; set; }
        public Nullable<int> CATEGORIESID { get; set; }
        public string EDITOR { get; set; }
        public Nullable<bool> ISIMAGE { get; set; }
        public Nullable<bool> ISARTICLE { get; set; }
    }
}
