//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAILQUEUE
    {
        public System.Guid ID { get; set; }
        public string MAILTO { get; set; }
        public string CC { get; set; }
        public string BCC { get; set; }
        public string SUBJECT { get; set; }
        public string BODY { get; set; }
        public Nullable<System.DateTime> SENDDATE { get; set; }
        public bool ISSENT { get; set; }
        public System.DateTime SENTDATE { get; set; }
        public byte ERRORCOUNT { get; set; }
    }
}
