//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public System.Guid ID { get; set; }
        public string NAME { get; set; }
        public string SURNAME { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
        public string PASSWORDRESETCODE { get; set; }
        public bool ISACTIVE { get; set; }
        public bool ISLOGIN { get; set; }
        public bool ISADMIN { get; set; }
        public string FULLNAME { get; set; }
    }
}
