//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUESTION
    {
        public int ID { get; set; }
        public string TITLE { get; set; }
        public string ANSWER { get; set; }
        public int SORT { get; set; }
        public bool ISACTIVE { get; set; }
    }
}
